version: '3.8'

services:
  http-backend:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.http-backend
    ports:
      - "3030:3030"
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
      - JWT_SECRET=local
    depends_on:
      - postgres
  websocket:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.websocket
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
      - JWT_SECRET=local
    depends_on:
      - postgres
      - redis

  frontend:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=local
    
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/usr/local/etc/redis 

volumes:
  postgres_data:
  redis_data: