FROM oven/bun:1

WORKDIR /app

COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json
COPY ./packages ./packages

COPY ./apps/http-backend/package.json ./apps/http-backend/package.json
RUN bun install


COPY ./apps/http-backend ./apps/http-backend



CMD [ "bun", "run", "docker:http-backend:start" ]