FROM oven/bun:1

WORKDIR /app

COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json
RUN bun install

COPY ./packages ./packages

COPY ./apps/http-backend/package.json ./apps/http-backend/package.json
RUN bun install





CMD [ "bun", "run", "docker:http-backend:start" ]