FROM oven/bun:1

WORKDIR /app

COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json
RUN bun install

COPY ./packages ./packages

COPY ./apps/websocket/package.json ./apps/websocket/package.json
RUN bun install



CMD [ "bun", "run", "docker:websocket:start" ]